package com.cpssoft.dev.zweb.type;

public enum GlAccountType {

	CASH_BANK, ACCOUNT_RECEIVABLE, INVENTORY, OTHER_CURRENT_ASSET, FIXED_ASSET, ACCUMULATED_DEPRECIATION, OTHER_ASSET, ACCOUNT_PAYABLE, OTHER_CURRENT_LIABILITY, LONG_TERM_LIABILITY, EQUITY, REVENUE, COST_OF_GOOD_SOLD, EXPENSE, OTHER_EXPENSE, OTHER_INCOME;
}
